version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: feedback_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 core.asgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DB_HOST=db
      - DB_NAME=feedback_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres

volumes:
  postgres_data:
