services:
  - type: web
    name: milan-backend
    env: python
    plan: free
    rootDir: milan/backend
    buildCommand: ./build.sh
    startCommand: daphne -b 0.0.0.0 -p $PORT core.asgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: feedback_grk6
          property: connectionString

  - type: pserv
    name: feedback_grk6
    env: postgresql
    plan: free
    databaseName: feedback_grk6
    databaseUser: feedback_user