# Generated by Django 4.2.7 on 2025-06-24 06:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterModelTable(
            name='feedback',
            table='feedback_feedback',
        ),
        migrations.AlterModelTable(
            name='user',
            table='feedback_user',
        ),
    ]
